apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"
jobs:
  ci-job:
    steps:
    - uses: cloudbees-io/checkout@v1
      name: checkout
    - uses: docker://golang:1.20
      name: Build Go app
      run: |
        go build -v ./...
    - uses: docker://golang:1.20
      name: Run tests
      run: |
        go test -v ./...
    - id: dockerconfig
      name: Configure container registry credentials
      uses: cloudbees-io/configure-oci-credentials@v0
      with:
        registry: ${{ vars.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}