apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"
jobs:
  ci-job:
    steps:
    - id: dockerconfig
      name: Configure container registry credentials
      uses: cloudbees-io/configure-oci-credentials@v1
      with:
        registry: ${{ vars.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: cloudbees-io/checkout@v1
      name: checkout

    - uses: docker://golang:1.20
      name: Build Go app
      run: |
        go build -v ./...

    - uses: docker://golang:1.20
      name: Run tests
      run: |
        go test -v ./...
        
    - id: build-image
      name: Build spacely image
      uses: cloudbees-io/kaniko@1ea4047fb3a7ad3eaaec889e4d8389743243496b17e68cdbd6a8908a16ca88ae
      with:
        dockerfile: Dockerfile
        destination: ${{ vars.DOCKER_REGISTRY }}:latest
        context: ${{ cloudbees.workspace }}