apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"
jobs:
  ci-job:
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - uses: cloudbees-io/checkout@v1
        name: checkout
      - uses: docker://golang:1.20
        name: Build Go app
        run: |
          go build -v ./...
      - uses: docker://golang:1.20
        name: Run tests
        run: |
          go test -v ./...
      - uses: docker://alpine:3.19
        name: Test vars
        run: |
          echo -e "commit: ${{ cloudbees.scm.sha }}"